

var INDEXES = [
    ["(None)", "(None)"],
    
    ["Name", "Name"] 
];

var INDEX_VALUES = {
    "(None)": [],
    
    "Name": [
        
        ["Abbott, Edwin Abbott", "Abbott, Edwin Abbott"] ,
        ["Aesop", "Aesop"] ,
        ["Aguado, Pedro de, active 16th century", "Aguado, Pedro de, active 16th century"] ,
        ["Alcott, Louisa May", "Alcott, Louisa May"] ,
        ["Ali Haydar Mithat", "Ali Haydar Mithat"] ,
        ["Allen, James", "Allen, James"] ,
        ["Andersen, H. C. (Hans Christian)", "Andersen, H. C. (Hans Christian)"] ,
        ["Anderson, Poul", "Anderson, Poul"] ,
        ["Anonymous", "Anonymous"] ,
        ["Anvil, Christopher", "Anvil, Christopher"] ,
        ["Apicius", "Apicius"] ,
        ["Apollonius, Rhodius", "Apollonius, Rhodius"] ,
        ["Apuleius", "Apuleius"] ,
        ["Aristophanes", "Aristophanes"] ,
        ["Aristotle", "Aristotle"] ,
        ["Arkin, Alan", "Arkin, Alan"] ,
        ["Asimov, Isaac", "Asimov, Isaac"] ,
        ["Augustine, Saint, Bishop of Hippo", "Augustine, Saint, Bishop of Hippo"] ,
        ["Austen, Jane", "Austen, Jane"] ,
        ["Babcock & Wilcox Company", "Babcock & Wilcox Company"] ,
        ["Bacon, Francis", "Bacon, Francis"] ,
        ["Bade, William L.", "Bade, William L."] ,
        ["Balagtas, Francisco", "Balagtas, Francisco"] ,
        ["Baldwin, James", "Baldwin, James"] ,
        ["Balfour, Lady Frances", "Balfour, Lady Frances"] ,
        ["Ballantyne, R. M. (Robert Michael)", "Ballantyne, R. M. (Robert Michael)"] ,
        ["Balzac, Honor de", "Balzac, Honor de"] ,
        ["Barnum, P. T. (Phineas Taylor)", "Barnum, P. T. (Phineas Taylor)"] ,
        ["Barr, Stephen", "Barr, Stephen"] ,
        ["Barrie, J. M. (James Matthew)", "Barrie, J. M. (James Matthew)"] ,
        ["Baudelaire, Charles", "Baudelaire, Charles"] ,
        ["Baum, L. Frank (Lyman Frank)", "Baum, L. Frank (Lyman Frank)"] ,
        ["Bdier, Joseph", "Bdier, Joseph"] ,
        ["Bede, the Venerable, Saint", "Bede, the Venerable, Saint"] ,
        ["Beethoven, Ludwig van", "Beethoven, Ludwig van"] ,
        ["Behn, Aphra", "Behn, Aphra"] ,
        ["Bellamy, Edward", "Bellamy, Edward"] ,
        ["Belloc, Hilaire", "Belloc, Hilaire"] ,
        ["Benedict, Ralph Paine", "Benedict, Ralph Paine"] ,
        ["Bennett, Arnold", "Bennett, Arnold"] ,
        ["Bennett, Charles E. (Charles Edwin)", "Bennett, Charles E. (Charles Edwin)"] ,
        ["Benson, Robert Hugh", "Benson, Robert Hugh"] ,
        ["Berens, E. M.", "Berens, E. M."] ,
        ["Bergerac, Savinien de Cyrano de", "Bergerac, Savinien de Cyrano de"] ,
        ["Bergson, Henri", "Bergson, Henri"] ,
        ["Bierce, Ambrose", "Bierce, Ambrose"] ,
        ["Blackwood, Algernon", "Blackwood, Algernon"] ,
        ["Blake, William", "Blake, William"] ,
        ["Bleyer, Willard Grosvenor", "Bleyer, Willard Grosvenor"] ,
        ["Blomberg, Con", "Blomberg, Con"] ,
        ["Blount, James H. (James Henderson)", "Blount, James H. (James Henderson)"] ,
        ["Boccaccio, Giovanni", "Boccaccio, Giovanni"] ,
        ["Boethius", "Boethius"] ,
        ["Boldrewood, Rolf", "Boldrewood, Rolf"] ,
        ["Bone, Jesse F. (Jesse Franklin)", "Bone, Jesse F. (Jesse Franklin)"] ,
        ["Boswell, James", "Boswell, James"] ,
        ["Bourrienne, Louis Antoine Fauvelet de", "Bourrienne, Louis Antoine Fauvelet de"] ,
        ["Boy Scouts of America", "Boy Scouts of America"] ,
        ["Bradbury, Ray", "Bradbury, Ray"] ,
        ["Braddon, M. E. (Mary Elizabeth)", "Braddon, M. E. (Mary Elizabeth)"] ,
        ["Bradford, William", "Bradford, William"] ,
        ["Bradley, A. C. (Andrew Cecil)", "Bradley, A. C. (Andrew Cecil)"] ,
        ["Bridges, Calvin B. (Calvin Blackman)", "Bridges, Calvin B. (Calvin Blackman)"] ,
        ["Bront, Anne", "Bront, Anne"] ,
        ["Bront, Charlotte", "Bront, Charlotte"] ,
        ["Bront, Emily", "Bront, Emily"] ,
        ["Brooke, L. Leslie (Leonard Leslie)", "Brooke, L. Leslie (Leonard Leslie)"] ,
        ["Browning, Elizabeth Barrett", "Browning, Elizabeth Barrett"] ,
        ["Browning, Robert", "Browning, Robert"] ,
        ["Buchan, John", "Buchan, John"] ,
        ["Bunyan, John", "Bunyan, John"] ,
        ["Burke, Edmund", "Burke, Edmund"] ,
        ["Burnett, Frances Hodgson", "Burnett, Frances Hodgson"] ,
        ["Burroughs, Edgar Rice", "Burroughs, Edgar Rice"] ,
        ["Burton, Robert", "Burton, Robert"] ,
        ["Byron, George Gordon Byron, Baron", "Byron, George Gordon Byron, Baron"] ,
        ["Caesar, Julius", "Caesar, Julius"] ,
        ["Caldern de la Barca, Pedro", "Caldern de la Barca, Pedro"] ,
        ["Cao, Xueqin", "Cao, Xueqin"] ,
        ["Carlyle, Thomas", "Carlyle, Thomas"] ,
        ["Carnegie, Andrew", "Carnegie, Andrew"] ,
        ["Carroll, Lewis", "Carroll, Lewis"] ,
        ["Casas, Bartolom de las", "Casas, Bartolom de las"] ,
        ["Castle, Egerton", "Castle, Egerton"] ,
        ["Cather, Willa", "Cather, Willa"] ,
        ["Cervantes Saavedra, Miguel de", "Cervantes Saavedra, Miguel de"] ,
        ["Chambers, Robert W. (Robert William)", "Chambers, Robert W. (Robert William)"] ,
        ["Chaucer, Geoffrey", "Chaucer, Geoffrey"] ,
        ["Cheiro", "Cheiro"] ,
        ["Chekhov, Anton Pavlovich", "Chekhov, Anton Pavlovich"] ,
        ["Chesterfield, Philip Dormer Stanhope, Earl of", "Chesterfield, Philip Dormer Stanhope, Earl of"] ,
        ["Chesterton, G. K. (Gilbert Keith)", "Chesterton, G. K. (Gilbert Keith)"] ,
        ["Christie, Agatha", "Christie, Agatha"] ,
        ["Chrtien, de Troyes, active 12th century", "Chrtien, de Troyes, active 12th century"] ,
        ["Cicero, Marcus Tullius", "Cicero, Marcus Tullius"] ,
        ["Claudianus, Claudius", "Claudianus, Claudius"] ,
        ["Clausewitz, Carl von", "Clausewitz, Carl von"] ,
        ["Clay, Albert Tobias", "Clay, Albert Tobias"] ,
        ["Cleland, John", "Cleland, John"] ,
        ["Cody, Sherwin", "Cody, Sherwin"] ,
        ["Coleridge, Samuel Taylor", "Coleridge, Samuel Taylor"] ,
        ["Collins, Wilkie", "Collins, Wilkie"] ,
        ["Collodi, Carlo", "Collodi, Carlo"] ,
        ["Confucius", "Confucius"] ,
        ["Congreve, William", "Congreve, William"] ,
        ["Conrad, Joseph", "Conrad, Joseph"] ,
        ["Cook, James", "Cook, James"] ,
        ["Cook, John R.", "Cook, John R."] ,
        ["Coppel, Alfred", "Coppel, Alfred"] ,
        ["Craig, Austin", "Craig, Austin"] ,
        ["Crane, Stephen", "Crane, Stephen"] ,
        ["Crane, Walter", "Crane, Walter"] ,
        ["D'Ooge, Benjamin L. (Benjamin Leonard)", "D'Ooge, Benjamin L. (Benjamin Leonard)"] ,
        ["Dante Alighieri", "Dante Alighieri"] ,
        ["Darwin, Charles", "Darwin, Charles"] ,
        ["Dasgupta, Surendranath", "Dasgupta, Surendranath"] ,
        ["Davies, W. H. (William Henry)", "Davies, W. H. (William Henry)"] ,
        ["Davis, Rebecca Harding", "Davis, Rebecca Harding"] ,
        ["Daz del Castillo, Bernal", "Daz del Castillo, Bernal"] ,
        ["De Quincey, Thomas", "De Quincey, Thomas"] ,
        ["Defoe, Daniel", "Defoe, Daniel"] ,
        ["Dehan, Richard", "Dehan, Richard"] ,
        ["Dewey, John", "Dewey, John"] ,
        ["Dick, Philip K.", "Dick, Philip K."] ,
        ["Dickens, Charles", "Dickens, Charles"] ,
        ["Dickinson, Emily", "Dickinson, Emily"] ,
        ["Domville-Fife, Charles William", "Domville-Fife, Charles William"] ,
        ["Dostoyevsky, Fyodor", "Dostoyevsky, Fyodor"] ,
        ["Douglass, Frederick", "Douglass, Frederick"] ,
        ["Dow, Arthur Wesley", "Dow, Arthur Wesley"] ,
        ["Doyle, Arthur Conan", "Doyle, Arthur Conan"] ,
        ["Dryfoos, Dave", "Dryfoos, Dave"] ,
        ["Du Bois, W. E. B. (William Edward Burghardt)", "Du Bois, W. E. B. (William Edward Burghardt)"] ,
        ["Dudeney, Henry Ernest", "Dudeney, Henry Ernest"] ,
        ["Dumas, Alexandre", "Dumas, Alexandre"] ,
        ["Dunbar, Paul Laurence", "Dunbar, Paul Laurence"] ,
        ["Duncan, A. W.", "Duncan, A. W."] ,
        ["Durkheim, mile", "Durkheim, mile"] ,
        ["Einstein, Albert", "Einstein, Albert"] ,
        ["Eliot, George", "Eliot, George"] ,
        ["Eliot, T. S. (Thomas Stearns)", "Eliot, T. S. (Thomas Stearns)"] ,
        ["Ellanby, Boyd", "Ellanby, Boyd"] ,
        ["Ellis, Havelock", "Ellis, Havelock"] ,
        ["Emanuel, Walter", "Emanuel, Walter"] ,
        ["Emerson, Ralph Waldo", "Emerson, Ralph Waldo"] ,
        ["Engels, Friedrich", "Engels, Friedrich"] ,
        ["Ennis, William Duane", "Ennis, William Duane"] ,
        ["Equiano, Olaudah", "Equiano, Olaudah"] ,
        ["Erasmus, Desiderius", "Erasmus, Desiderius"] ,
        ["Esenwein, J. Berg (Joseph Berg)", "Esenwein, J. Berg (Joseph Berg)"] ,
        ["Euripides", "Euripides"] ,
        ["Evans, Dean", "Evans, Dean"] ,
        ["Fairham, William", "Fairham, William"] ,
        ["Farley, Frank Edgar", "Farley, Frank Edgar"] ,
        ["Ferguson, S. C.", "Ferguson, S. C."] ,
        ["Fernald, James Champlin", "Fernald, James Champlin"] ,
        ["Fetler, Andrew", "Fetler, Andrew"] ,
        ["Fielding, Henry", "Fielding, Henry"] ,
        ["Fisher, David E.", "Fisher, David E."] ,
        ["Fitch, Charles", "Fitch, Charles"] ,
        ["Fitzgerald, F. Scott (Francis Scott)", "Fitzgerald, F. Scott (Francis Scott)"] ,
        ["Flaubert, Gustave", "Flaubert, Gustave"] ,
        ["Ford, Ford Madox", "Ford, Ford Madox"] ,
        ["Ford, Henry", "Ford, Henry"] ,
        ["Forster, E. M. (Edward Morgan)", "Forster, E. M. (Edward Morgan)"] ,
        ["Fox-Davies, Arthur Charles", "Fox-Davies, Arthur Charles"] ,
        ["Foxe, John", "Foxe, John"] ,
        ["Franklin, Benjamin", "Franklin, Benjamin"] ,
        ["Frazer, James George", "Frazer, James George"] ,
        ["Freud, Sigmund", "Freud, Sigmund"] ,
        ["Frost, Robert", "Frost, Robert"] ,
        ["Galsworthy, John", "Galsworthy, John"] ,
        ["Gaskell, Elizabeth Cleghorn", "Gaskell, Elizabeth Cleghorn"] ,
        ["Gibbon, Edward", "Gibbon, Edward"] ,
        ["Gibbs, George", "Gibbs, George"] ,
        ["Gibran, Kahlil", "Gibran, Kahlil"] ,
        ["Gibson, Joe", "Gibson, Joe"] ,
        ["Gilbert, W. S. (William Schwenck)", "Gilbert, W. S. (William Schwenck)"] ,
        ["Gilman, Charlotte Perkins", "Gilman, Charlotte Perkins"] ,
        ["Glaspell, Susan", "Glaspell, Susan"] ,
        ["Godbey, Allen Howard", "Godbey, Allen Howard"] ,
        ["Goethe, Johann Wolfgang von", "Goethe, Johann Wolfgang von"] ,
        ["Gogol, Nikolai Vasilevich", "Gogol, Nikolai Vasilevich"] ,
        ["Goldsmith, Oliver", "Goldsmith, Oliver"] ,
        ["Goudiss, C. Houston (Charles Houston)", "Goudiss, C. Houston (Charles Houston)"] ,
        ["Grahame, Kenneth", "Grahame, Kenneth"] ,
        ["Grant, Ulysses S. (Ulysses Simpson)", "Grant, Ulysses S. (Ulysses Simpson)"] ,
        ["Grimm, Jacob", "Grimm, Jacob"] ,
        ["Grimm, Wilhelm", "Grimm, Wilhelm"] ,
        ["Grose, Francis", "Grose, Francis"] ,
        ["Grossmith, Weedon", "Grossmith, Weedon"] ,
        ["Guerber, H. A. (Hlne Adeline)", "Guerber, H. A. (Hlne Adeline)"] ,
        ["Haggard, H. Rider (Henry Rider)", "Haggard, H. Rider (Henry Rider)"] ,
        ["Haggert, W. T.", "Haggert, W. T."] ,
        ["Hall, Jennie", "Hall, Jennie"] ,
        ["Hamsun, Knut", "Hamsun, Knut"] ,
        ["Hardy, Osgood", "Hardy, Osgood"] ,
        ["Hardy, Thomas", "Hardy, Thomas"] ,
        ["Harmon, Jim", "Harmon, Jim"] ,
        ["Harris, Joel Chandler", "Harris, Joel Chandler"] ,
        ["Harte, Bret", "Harte, Bret"] ,
        ["Hartley, Cecil B.", "Hartley, Cecil B."] ,
        ["Hartley, Florence", "Hartley, Florence"] ,
        ["Hauptmann, Gerhart", "Hauptmann, Gerhart"] ,
        ["Hawthorne, Nathaniel", "Hawthorne, Nathaniel"] ,
        ["Hazelton, Harry", "Hazelton, Harry"] ,
        ["Hegel, Georg Wilhelm Friedrich", "Hegel, Georg Wilhelm Friedrich"] ,
        ["Henry, O.", "Henry, O."] ,
        ["Herodotus", "Herodotus"] ,
        ["Hesiod", "Hesiod"] ,
        ["Hesse, Hermann", "Hesse, Hermann"] ,
        ["Hfiz, 14th cent.", "Hfiz, 14th cent."] ,
        ["Hill, John A. (John Alexander)", "Hill, John A. (John Alexander)"] ,
        ["Hlose", "Hlose"] ,
        ["Hobbes, Thomas", "Hobbes, Thomas"] ,
        ["Hodgson, William Hope", "Hodgson, William Hope"] ,
        ["Hoffmann, Heinrich", "Hoffmann, Heinrich"] ,
        ["Hogarth, William", "Hogarth, William"] ,
        ["Holbrook, Kennedy", "Holbrook, Kennedy"] ,
        ["Holmes, George Charles Vincent, Sir", "Holmes, George Charles Vincent, Sir"] ,
        ["Holmes, Oliver Wendell", "Holmes, Oliver Wendell"] ,
        ["Homer", "Homer"] ,
        ["Hooke, Robert", "Hooke, Robert"] ,
        ["Hoover, Thomas", "Hoover, Thomas"] ,
        ["Hotten, John Camden", "Hotten, John Camden"] ,
        ["Housman, A. E. (Alfred Edward)", "Housman, A. E. (Alfred Edward)"] ,
        ["Hugo, Victor", "Hugo, Victor"] ,
        ["Hume, David", "Hume, David"] ,
        ["Huysmans, J.-K. (Joris-Karl)", "Huysmans, J.-K. (Joris-Karl)"] ,
        ["Ibsen, Henrik", "Ibsen, Henrik"] ,
        ["Irving, Washington", "Irving, Washington"] ,
        ["Jacob, P. L.", "Jacob, P. L."] ,
        ["Jacobs, Harriet A. (Harriet Ann)", "Jacobs, Harriet A. (Harriet Ann)"] ,
        ["Jacobs, Sylvia", "Jacobs, Sylvia"] ,
        ["Jacobs, W. W. (William Wymark)", "Jacobs, W. W. (William Wymark)"] ,
        ["James I, King of England", "James I, King of England"] ,
        ["James, Henry", "James, Henry"] ,
        ["James, M. R. (Montague Rhodes)", "James, M. R. (Montague Rhodes)"] ,
        ["James, William", "James, William"] ,
        ["Jay, John", "Jay, John"] ,
        ["Jenkins, Hester Donaldson", "Jenkins, Hester Donaldson"] ,
        ["Jermain, Frances", "Jermain, Frances"] ,
        ["Jerome, Jerome K. (Jerome Klapka)", "Jerome, Jerome K. (Jerome Klapka)"] ,
        ["Jewitt, Llewellynn Frederick William", "Jewitt, Llewellynn Frederick William"] ,
        ["Jimnez, Juan Ramn", "Jimnez, Juan Ramn"] ,
        ["Jnger, Ernst", "Jnger, Ernst"] ,
        ["Johnson, James Weldon", "Johnson, James Weldon"] ,
        ["Johnson, Samuel", "Johnson, Samuel"] ,
        ["Jonson, Ben", "Jonson, Ben"] ,
        ["Jordan, William George", "Jordan, William George"] ,
        ["Josephus, Flavius", "Josephus, Flavius"] ,
        ["Joyce, James", "Joyce, James"] ,
        ["Kafka, Franz", "Kafka, Franz"] ,
        ["Kant, Immanuel", "Kant, Immanuel"] ,
        ["Keller, Helen", "Keller, Helen"] ,
        ["Kellogg, John Azor", "Kellogg, John Azor"] ,
        ["Keynes, John Maynard", "Keynes, John Maynard"] ,
        ["King, L. W. (Leonard William)", "King, L. W. (Leonard William)"] ,
        ["King, Marshall", "King, Marshall"] ,
        ["Kipling, Rudyard", "Kipling, Rudyard"] ,
        ["Knight, E. F. (Edward Frederick)", "Knight, E. F. (Edward Frederick)"] ,
        ["Knowles, James, Sir", "Knowles, James, Sir"] ,
        ["Kornbluth, C. M. (Cyril M.)", "Kornbluth, C. M. (Cyril M.)"] ,
        ["Kurtz, J. H. (Johann Heinrich)", "Kurtz, J. H. (Johann Heinrich)"] ,
        ["La Rochefoucauld, Franois duc de", "La Rochefoucauld, Franois duc de"] ,
        ["Lang, Andrew", "Lang, Andrew"] ,
        ["Lanier, Sidney", "Lanier, Sidney"] ,
        ["Laozi", "Laozi"] ,
        ["Laumer, Keith", "Laumer, Keith"] ,
        ["Lawless, Emily", "Lawless, Emily"] ,
        ["Lawrence, D. H. (David Herbert)", "Lawrence, D. H. (David Herbert)"] ,
        ["Lawrence, of the Resurrection, Brother", "Lawrence, of the Resurrection, Brother"] ,
        ["Le Bon, Gustave", "Le Bon, Gustave"] ,
        ["Le Fanu, Joseph Sheridan", "Le Fanu, Joseph Sheridan"] ,
        ["Leadbeater, C. W. (Charles Webster)", "Leadbeater, C. W. (Charles Webster)"] ,
        ["Leiber, Fritz", "Leiber, Fritz"] ,
        ["Leibniz, Gottfried Wilhelm, Freiherr von", "Leibniz, Gottfried Wilhelm, Freiherr von"] ,
        ["Leighton, Marie Connor", "Leighton, Marie Connor"] ,
        ["Leonardo, da Vinci", "Leonardo, da Vinci"] ,
        ["Leroux, Gaston", "Leroux, Gaston"] ,
        ["Lewis, M. G. (Matthew Gregory)", "Lewis, M. G. (Matthew Gregory)"] ,
        ["Lewis, Sinclair", "Lewis, Sinclair"] ,
        ["Lippmann, Walter", "Lippmann, Walter"] ,
        ["Litchfield, Frederick", "Litchfield, Frederick"] ,
        ["Livy", "Livy"] ,
        ["Locke, John", "Locke, John"] ,
        ["Lofting, Hugh", "Lofting, Hugh"] ,
        ["London, Jack", "London, Jack"] ,
        ["Long, C. C.", "Long, C. C."] ,
        ["Long, William J. (William Joseph)", "Long, William J. (William Joseph)"] ,
        ["Longinus, 1st cent.", "Longinus, 1st cent."] ,
        ["Loti, Pierre", "Loti, Pierre"] ,
        ["Lovecraft, H. P. (Howard Phillips)", "Lovecraft, H. P. (Howard Phillips)"] ,
        ["Luce, Edmund", "Luce, Edmund"] ,
        ["Macadam, Robert K.", "Macadam, Robert K."] ,
        ["MacCulloch, J. A. (John Arnott)", "MacCulloch, J. A. (John Arnott)"] ,
        ["MacDonald, George", "MacDonald, George"] ,
        ["Macfarlane, Wallace", "Macfarlane, Wallace"] ,
        ["Machen, Arthur", "Machen, Arthur"] ,
        ["Machiavelli, Niccol", "Machiavelli, Niccol"] ,
        ["Mackay, Charles", "Mackay, Charles"] ,
        ["Mackay, Helen", "Mackay, Helen"] ,
        ["Mackenzie, Alexander", "Mackenzie, Alexander"] ,
        ["Mackenzie, Donald A. (Donald Alexander)", "Mackenzie, Donald A. (Donald Alexander)"] ,
        ["Mahan, A. T. (Alfred Thayer)", "Mahan, A. T. (Alfred Thayer)"] ,
        ["Mann, Thomas", "Mann, Thomas"] ,
        ["Mansfield, Katherine", "Mansfield, Katherine"] ,
        ["March, Francis Andrew", "March, Francis Andrew"] ,
        ["Marcus Aurelius, Emperor of Rome", "Marcus Aurelius, Emperor of Rome"] ,
        ["Marie, Queen of Rumania", "Marie, Queen of Rumania"] ,
        ["Marks, Winston K.", "Marks, Winston K."] ,
        ["Marlowe, Christopher", "Marlowe, Christopher"] ,
        ["Marlowe, Stephen", "Marlowe, Stephen"] ,
        ["Martin, Martha Evans", "Martin, Martha Evans"] ,
        ["Masters, Edgar Lee", "Masters, Edgar Lee"] ,
        ["Matthews, Stanley R.", "Matthews, Stanley R."] ,
        ["Maugham, W. Somerset (William Somerset)", "Maugham, W. Somerset (William Somerset)"] ,
        ["Maupassant, Guy de", "Maupassant, Guy de"] ,
        ["McGuffey, William Holmes", "McGuffey, William Holmes"] ,
        ["Melville, Herman", "Melville, Herman"] ,
        ["Mill, John Stuart", "Mill, John Stuart"] ,
        ["Miller, R. DeWitt", "Miller, R. DeWitt"] ,
        ["Milne, A. A. (Alan Alexander)", "Milne, A. A. (Alan Alexander)"] ,
        ["Milton, John", "Milton, John"] ,
        ["Mller, F. Max (Friedrich Max)", "Mller, F. Max (Friedrich Max)"] ,
        ["Molire", "Molire"] ,
        ["Montaigne, Michel de", "Montaigne, Michel de"] ,
        ["Montessori, Maria", "Montessori, Maria"] ,
        ["Montgomery, L. M. (Lucy Maud)", "Montgomery, L. M. (Lucy Maud)"] ,
        ["More, Thomas, Saint", "More, Thomas, Saint"] ,
        ["Morse, Katharine Duncan", "Morse, Katharine Duncan"] ,
        ["Mozart, Wolfgang Amadeus", "Mozart, Wolfgang Amadeus"] ,
        ["Murray, Charles Theodore", "Murray, Charles Theodore"] ,
        ["Nesbit, E. (Edith)", "Nesbit, E. (Edith)"] ,
        ["Neville, Kris", "Neville, Kris"] ,
        ["Newman, Louis", "Newman, Louis"] ,
        ["Newton, Isaac, Sir", "Newton, Isaac, Sir"] ,
        ["Nicomedia, Arrian of", "Nicomedia, Arrian of"] ,
        ["Nietzsche, Friedrich Wilhelm", "Nietzsche, Friedrich Wilhelm"] ,
        ["No Author Available", "No Author Available"] ,
        ["Noe, Sydney P.", "Noe, Sydney P."] ,
        ["Norris, Frank", "Norris, Frank"] ,
        ["Northup, Solomon", "Northup, Solomon"] ,
        ["Nourse, Alan Edward", "Nourse, Alan Edward"] ,
        ["Okakura, Kakuzo", "Okakura, Kakuzo"] ,
        ["Omar Khayyam", "Omar Khayyam"] ,
        ["Orczy, Emmuska Orczy, Baroness", "Orczy, Emmuska Orczy, Baroness"] ,
        ["Ossendowski, Ferdynand Antoni", "Ossendowski, Ferdynand Antoni"] ,
        ["Ouida", "Ouida"] ,
        ["Ovid", "Ovid"] ,
        ["Ozaki, Yei Theodora", "Ozaki, Yei Theodora"] ,
        ["Paine, Thomas", "Paine, Thomas"] ,
        ["Pangborn, Edgar", "Pangborn, Edgar"] ,
        ["Pascal, Blaise", "Pascal, Blaise"] ,
        ["Patajali", "Patajali"] ,
        ["Pearson, Emily Clemens", "Pearson, Emily Clemens"] ,
        ["Percival, Kate", "Percival, Kate"] ,
        ["Perrault, Charles", "Perrault, Charles"] ,
        ["Petronius Arbiter", "Petronius Arbiter"] ,
        ["Plato", "Plato"] ,
        ["Pliny, the Younger", "Pliny, the Younger"] ,
        ["Plutarch", "Plutarch"] ,
        ["Poe, Edgar Allan", "Poe, Edgar Allan"] ,
        ["Pohl, Frederik", "Pohl, Frederik"] ,
        ["Polidori, John William", "Polidori, John William"] ,
        ["Pope, Alexander", "Pope, Alexander"] ,
        ["Porter, Eleanor H. (Eleanor Hodgman)", "Porter, Eleanor H. (Eleanor Hodgman)"] ,
        ["Post, Emily", "Post, Emily"] ,
        ["Potter, Beatrix", "Potter, Beatrix"] ,
        ["Preston, Jack", "Preston, Jack"] ,
        ["Prince, Mary", "Prince, Mary"] ,
        ["Proust, Marcel", "Proust, Marcel"] ,
        ["Purdom, Tom", "Purdom, Tom"] ,
        ["Pyle, Howard", "Pyle, Howard"] ,
        ["Quattrocchi, Frank", "Quattrocchi, Frank"] ,
        ["Rabelais, Franois", "Rabelais, Franois"] ,
        ["Radcliffe, Ann Ward", "Radcliffe, Ann Ward"] ,
        ["Rand, Ayn", "Rand, Ayn"] ,
        ["Record, Samuel J. (Samuel James)", "Record, Samuel J. (Samuel James)"] ,
        ["Reynolds, George W. M. (George William MacArthur)", "Reynolds, George W. M. (George William MacArthur)"] ,
        ["Richardson, Samuel", "Richardson, Samuel"] ,
        ["Riis, Jacob A. (Jacob August)", "Riis, Jacob A. (Jacob August)"] ,
        ["Rilke, Rainer Maria", "Rilke, Rainer Maria"] ,
        ["Rizal, Jos", "Rizal, Jos"] ,
        ["Robinson, Frank M.", "Robinson, Frank M."] ,
        ["Roessler, Erwin W. (Erwin William)", "Roessler, Erwin W. (Erwin William)"] ,
        ["Rolleston, T. W. (Thomas William)", "Rolleston, T. W. (Thomas William)"] ,
        ["Rose, Joshua", "Rose, Joshua"] ,
        ["Rostand, Edmond", "Rostand, Edmond"] ,
        ["Rousseau, Jean-Jacques", "Rousseau, Jean-Jacques"] ,
        ["Rowlandson, Mary White", "Rowlandson, Mary White"] ,
        ["Roy, Lillian Elizabeth", "Roy, Lillian Elizabeth"] ,
        ["Ruskin, John", "Ruskin, John"] ,
        ["Russell, Bertrand", "Russell, Bertrand"] ,
        ["Russell, R. V. (Robert Vane)", "Russell, R. V. (Robert Vane)"] ,
        ["Rustichello of Pisa", "Rustichello of Pisa"] ,
        ["Sabatini, Rafael", "Sabatini, Rafael"] ,
        ["Sacher-Masoch, Leopold, Ritter von", "Sacher-Masoch, Leopold, Ritter von"] ,
        ["Saki", "Saki"] ,
        ["Salten, Felix", "Salten, Felix"] ,
        ["Samachson, Joseph", "Samachson, Joseph"] ,
        ["Sanborn, F. B.", "Sanborn, F. B."] ,
        ["Sanger, William W.", "Sanger, William W."] ,
        ["Santayana, George", "Santayana, George"] ,
        ["Scammell, John Chilton", "Scammell, John Chilton"] ,
        ["Schopenhauer, Arthur", "Schopenhauer, Arthur"] ,
        ["Scott, Walter", "Scott, Walter"] ,
        ["Sears, George Washington", "Sears, George Washington"] ,
        ["Sewell, Anna", "Sewell, Anna"] ,
        ["Shaara, Michael", "Shaara, Michael"] ,
        ["Shakespeare, William", "Shakespeare, William"] ,
        ["Sharkey, Jack", "Sharkey, Jack"] ,
        ["Shaw, Bernard", "Shaw, Bernard"] ,
        ["Shaw, Milton", "Shaw, Milton"] ,
        ["Shelley, Mary Wollstonecraft", "Shelley, Mary Wollstonecraft"] ,
        ["Shelley, Percy Bysshe", "Shelley, Percy Bysshe"] ,
        ["Sheridan, Richard Brinsley", "Sheridan, Richard Brinsley"] ,
        ["Sherman, William T. (William Tecumseh)", "Sherman, William T. (William Tecumseh)"] ,
        ["Silverberg, Robert", "Silverberg, Robert"] ,
        ["Sinclair, Upton", "Sinclair, Upton"] ,
        ["Skeat, Walter W. (Walter William)", "Skeat, Walter W. (Walter William)"] ,
        ["Smith, E. E. (Edward Elmer)", "Smith, E. E. (Edward Elmer)"] ,
        ["Smith, Evelyn E.", "Smith, Evelyn E."] ,
        ["Smith, Phyllis Sterling", "Smith, Phyllis Sterling"] ,
        ["Snorri Sturluson", "Snorri Sturluson"] ,
        ["Sophocles", "Sophocles"] ,
        ["Speed, Harold", "Speed, Harold"] ,
        ["Spenser, Edmund", "Spenser, Edmund"] ,
        ["Spinoza, Benedictus de", "Spinoza, Benedictus de"] ,
        ["Spyri, Johanna", "Spyri, Johanna"] ,
        ["Stamers, James", "Stamers, James"] ,
        ["Standing, Percy Cross", "Standing, Percy Cross"] ,
        ["Stecher, L.J.", "Stecher, L.J."] ,
        ["Stein, Gertrude", "Stein, Gertrude"] ,
        ["Stephens, James", "Stephens, James"] ,
        ["Sterne, Laurence", "Sterne, Laurence"] ,
        ["Stevenson, Robert Louis", "Stevenson, Robert Louis"] ,
        ["Still, William", "Still, William"] ,
        ["Stoker, Bram", "Stoker, Bram"] ,
        ["Stowe, Harriet Beecher", "Stowe, Harriet Beecher"] ,
        ["Stratton, Stephen S. (Stephen Samuel)", "Stratton, Stephen S. (Stephen Samuel)"] ,
        ["Strunk, William", "Strunk, William"] ,
        ["Suetonius", "Suetonius"] ,
        ["Sunzi, active 6th century B.C.", "Sunzi, active 6th century B.C."] ,
        ["Swift, Jonathan", "Swift, Jonathan"] ,
        ["Synge, J. M. (John Millington)", "Synge, J. M. (John Millington)"] ,
        ["Tacitus, Cornelius", "Tacitus, Cornelius"] ,
        ["Tagore, Rabindranath", "Tagore, Rabindranath"] ,
        ["Talbot, William Henry Fox", "Talbot, William Henry Fox"] ,
        ["Talmage, James E. (James Edward)", "Talmage, James E. (James Edward)"] ,
        ["Tennyson, Alfred Tennyson, Baron", "Tennyson, Alfred Tennyson, Baron"] ,
        ["Thomson, J. Arthur (John Arthur)", "Thomson, J. Arthur (John Arthur)"] ,
        ["Thoreau, Henry David", "Thoreau, Henry David"] ,
        ["Thurston, Edgar", "Thurston, Edgar"] ,
        ["Titchener, Edward Bradford", "Titchener, Edward Bradford"] ,
        ["Tocqueville, Alexis de", "Tocqueville, Alexis de"] ,
        ["Tolstoy, Leo, graf", "Tolstoy, Leo, graf"] ,
        ["Topham, Anne", "Topham, Anne"] ,
        ["Torrey, R. A. (Reuben Archer)", "Torrey, R. A. (Reuben Archer)"] ,
        ["Tozer, A. W. (Aiden Wilson)", "Tozer, A. W. (Aiden Wilson)"] ,
        ["Trevelyan, George Otto", "Trevelyan, George Otto"] ,
        ["Trollope, Anthony", "Trollope, Anthony"] ,
        ["Turner, Frederick Jackson", "Turner, Frederick Jackson"] ,
        ["Twain, Mark", "Twain, Mark"] ,
        ["Ukers, William H. (William Harrison)", "Ukers, William H. (William Harrison)"] ,
        ["United States. Office of Strategic Services", "United States. Office of Strategic Services"] ,
        ["Unknown", "Unknown"] ,
        ["Valmiki", "Valmiki"] ,
        ["Van Dyke, John Charles", "Van Dyke, John Charles"] ,
        ["Van Loon, Hendrik Willem", "Van Loon, Hendrik Willem"] ,
        ["Various", "Various"] ,
        ["Vatsyayana", "Vatsyayana"] ,
        ["Vereshchagin, Vasilii Vasilevich", "Vereshchagin, Vasilii Vasilevich"] ,
        ["Verne, Jules", "Verne, Jules"] ,
        ["Virgil", "Virgil"] ,
        ["Vitruvius Pollio", "Vitruvius Pollio"] ,
        ["Voltaire", "Voltaire"] ,
        ["Vonnegut, Kurt", "Vonnegut, Kurt"] ,
        ["Wallace, F. L. (Floyd L.)", "Wallace, F. L. (Floyd L.)"] ,
        ["Wallace, Lew", "Wallace, Lew"] ,
        ["Walpole, Horace", "Walpole, Horace"] ,
        ["Ward, Grady", "Ward, Grady"] ,
        ["Washington, Booker T.", "Washington, Booker T."] ,
        ["Waugh, Alec", "Waugh, Alec"] ,
        ["Webb, James Morris", "Webb, James Morris"] ,
        ["Webster, Jean", "Webster, Jean"] ,
        ["Webster, John", "Webster, John"] ,
        ["Wells, Carolyn", "Wells, Carolyn"] ,
        ["Wells, H. G. (Herbert George)", "Wells, H. G. (Herbert George)"] ,
        ["Wells-Barnett, Ida B.", "Wells-Barnett, Ida B."] ,
        ["Werner, E. T. C. (Edward Theodore Chalmers)", "Werner, E. T. C. (Edward Theodore Chalmers)"] ,
        ["Wesley, Joseph", "Wesley, Joseph"] ,
        ["Westerman, Percy F. (Percy Francis)", "Westerman, Percy F. (Percy Francis)"] ,
        ["Wharton, Edith", "Wharton, Edith"] ,
        ["Whitman, Walt", "Whitman, Walt"] ,
        ["Whyte, Adam Gowens", "Whyte, Adam Gowens"] ,
        ["Wilde, Oscar", "Wilde, Oscar"] ,
        ["Wilkins, W. H. (William Henry)", "Wilkins, W. H. (William Henry)"] ,
        ["Windsor, H. H. (Henry Haven)", "Windsor, H. H. (Henry Haven)"] ,
        ["Wister, Owen", "Wister, Owen"] ,
        ["Wodehouse, P. G. (Pelham Grenville)", "Wodehouse, P. G. (Pelham Grenville)"] ,
        ["Wollstonecraft, Mary", "Wollstonecraft, Mary"] ,
        ["Wood, Thomas", "Wood, Thomas"] ,
        ["Woolf, Virginia", "Woolf, Virginia"] ,
        ["Wordsworth, William", "Wordsworth, William"] ,
        ["Wyss, Johann David", "Wyss, Johann David"] ,
        ["Xenophon", "Xenophon"] ,
        ["Zola, mile", "Zola, mile"] 
    ]
    
}

var PROPERTIES = [
    ["Birth", "Birth"] ,
    ["Death", "Death"] ,
    ["Name", "Name"] ,
    ["Day", "Day"] ,
    ["Full Date", "Full Date"] ,
    ["Month", "Month"] ,
    ["Month Name", "Month Name"] ,
    ["Year", "Year"] ,
    ["Title", "Title"] ,
    ["Type", "Type"] ,
    ["Total", "Total"] ,
    ["Downloads", "Downloads"] ,
    ["ID", "ID"] ,
    ["Rank", "Rank"] ,
    ["Url", "Url"] ,
    ["Automated Readability Index", "Automated Readability Index"] ,
    ["Coleman Liau Index", "Coleman Liau Index"] ,
    ["Dale Chall Readability Score", "Dale Chall Readability Score"] ,
    ["Difficult Words", "Difficult Words"] ,
    ["Flesch Kincaid Grade", "Flesch Kincaid Grade"] ,
    ["Flesch Reading Ease", "Flesch Reading Ease"] ,
    ["Gunning Fog", "Gunning Fog"] ,
    ["Linear Write Formula", "Linear Write Formula"] ,
    ["Smog Index", "Smog Index"] ,
    ["Polarity", "Polarity"] ,
    ["Subjectivity", "Subjectivity"] ,
    ["Average Letter per Word", "Average Letter per Word"] ,
    ["Average Sentence Length", "Average Sentence Length"] ,
    ["Average Sentence per Word", "Average Sentence per Word"] ,
    ["Characters", "Characters"] ,
    ["Polysyllables", "Polysyllables"] ,
    ["Sentences", "Sentences"] ,
    ["Syllables", "Syllables"] ,
    ["Words", "Words"] 
]

Blockly.Blocks['classics_get'] = {
  init: function() {
    this.setColour(WEATHER_HUE);
    this.appendDummyInput('MAIN')
        .appendField("classics.get")
        .appendField(new Blockly.FieldDropdown(PROPERTIES), "PROPERTY")
        .appendField("filter")
        .appendField(new Blockly.FieldDropdown(INDEXES, function(option) {
                        this.sourceBlock_.updateShape_(option);
                    }), "INDEX")
    this.updateShape_();
    this.setInputsInline(false);
    this.setOutput(true, "Array");
    this.setTooltip('Returns a list of Classics data.');
  },
  mutationToDom: function() {
    var container = document.createElement('mutation');
    container.setAttribute('index', this.getFieldValue('INDEX'));
    container.setAttribute('index_value', this.getFieldValue('INDEX_VALUE'));
    return container;
  },
  domToMutation: function(xmlElement) {
    var index = xmlElement.getAttribute('index');
    var index_value = xmlElement.getAttribute('index_value');
    this.updateShape_(index, index_value);
  },
  updateShape_: function(index, index_value) {
    var inputGroup = this.getInput('MAIN')
    var fieldExists = this.getField('INDEX_VALUE');
    if (fieldExists) {
        inputGroup.removeField('INDEX_VALUE');
    }
    this.setFieldValue(index, 'INDEX');
    if (index != undefined && index != '(None)') {
        inputGroup.appendField(new Blockly.FieldDropdown(INDEX_VALUES[index]), 'INDEX_VALUE')
        if (index_value != undefined) {
            this.setFieldValue(index_value, 'INDEX_VALUE');
        } else {
            console.log(INDEX_VALUES[index])
            this.setFieldValue(INDEX_VALUES[index][0][0], 'INDEX_VALUE');
        }
    }    
  }
};
Blockly.Python['classics_get'] = function(block) {
    Blockly.Python.definitions_['import_classics'] = 'import classics';
    var property = Blockly.Python.quote_(block.getFieldValue('PROPERTY'));
    var index_unquoted = block.getFieldValue('INDEX');
    var index = Blockly.Python.quote_(index_unquoted);
    var index_value = "''";
    if (index_unquoted != '(None)') {
        var iv = block.getFieldValue('INDEX_VALUE') || "";
        index_value = Blockly.Python.quote_(iv);
    }
    var code = 'classics.get('+property+',' +index+','+index_value+')';
    return [code, Blockly.Python.ORDER_ATOMIC];
};

PythonToBlocks.KNOWN_MODULES['classics'] = {
    "get": ["classics_get", 
            "PROPERTY", 
            {"type": "mutation", "name": "@INDEX"},
            {"type": "mutation", "name": "@INDEX_VALUE"}]
};

AbstractInterpreter.MODULES['classics'] = {
    'get': {"type": "List", "empty": false, "component": {"type": 'Num'}}
};