const PYTHON_BLOCK_TYPES = {
    NUMBER: "py_number",
    STRING: "py_string",
    BOOLEAN: "py_boolean",
    NONE: "py_none",
    VARIABLE: "py_variable",
    ASSIGN: "py_assign",
    ADD: "py_add",
    SUBTRACT: "py_subtract",
    MULTIPLY: "py_multiply",
    DIVIDE: "py_divide",
    MODULO: "py_modulo",
    POWER: "py_power",
    COMPARE: "py_compare",
    BOOL_OP: "py_bool_op",
    NOT: "py_not",
    IF: "py_if",
    WHILE: "py_while",
    WHILE_ELSE: "py_while_else",
    FOR: "py_for",
    FOR_ELSE: "py_for_else",
    FUNC_DEF: "py_func_def",
    FUNC_CALL: "py_func_call",
    RETURN: "py_return",
    PRINT: "py_print",
    LIST: "py_list",
    TUPLE: "py_tuple",
    DICT: "py_dict",
    COMPREHENSION: "py_comprehension",
    COMPREHENSION_FOR: "py_comprehension_for",
    COMPREHENSION_IF: "py_comprehension_if",
    INDEX: "py_index",
    ATTR: "py_attr",
    IMPORT: "py_import",
    EXPR_STMT: "py_expr_stmt",
    CST_EXPR: "py_cst_expr",
    CST_STMT: "py_cst_stmt",
    DECORATED: "py_decorated",
    TRY: "py_try",
    UNSUPPORTED: "py_unsupported",
    ERROR: "py_error"
};
export {
    PYTHON_BLOCK_TYPES
};
